# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detect_sticks.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QLabel{\n"
"color:rgb(255, 255,255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"border:0px;\n"
"background-color:#93C6FF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:5px;\n"
"border-color:rgb(170, 4, 7);\n"
"background-color: rgb(170, 4, 7);\n"
"}\n"
"QLabel{\n"
"font: 16pt \"Consolas\";\n"
"}\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(15, 5, 2, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_superior)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(477, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_minimize = QtWidgets.QPushButton(self.frame_superior)
        self.button_minimize.setMaximumSize(QtCore.QSize(30, 30))
        self.button_minimize.setStyleSheet("")
        self.button_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_minimize.setIcon(icon)
        self.button_minimize.setIconSize(QtCore.QSize(25, 25))
        self.button_minimize.setObjectName("button_minimize")
        self.horizontalLayout.addWidget(self.button_minimize)
        self.button_maximize = QtWidgets.QPushButton(self.frame_superior)
        self.button_maximize.setMaximumSize(QtCore.QSize(30, 30))
        self.button_maximize.setStyleSheet("")
        self.button_maximize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/maximizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_maximize.setIcon(icon1)
        self.button_maximize.setIconSize(QtCore.QSize(25, 25))
        self.button_maximize.setObjectName("button_maximize")
        self.horizontalLayout.addWidget(self.button_maximize)
        self.button_close = QtWidgets.QPushButton(self.frame_superior)
        self.button_close.setMaximumSize(QtCore.QSize(30, 30))
        self.button_close.setStyleSheet("")
        self.button_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon2)
        self.button_close.setIconSize(QtCore.QSize(25, 25))
        self.button_close.setObjectName("button_close")
        self.horizontalLayout.addWidget(self.button_close)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(self.frame)
        self.frame_inferior.setStyleSheet("")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_datos = QtWidgets.QFrame(self.frame_inferior)
        self.frame_datos.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_datos.setStyleSheet("QFrame{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"")
        self.frame_datos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_datos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_datos.setObjectName("frame_datos")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_datos)
        self.verticalLayout_4.setContentsMargins(15, 0, 10, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_botones = QtWidgets.QFrame(self.frame_datos)
        self.frame_botones.setStyleSheet("QFrame{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Consolas\";\n"
"color:rgb(255, 255,255);\n"
"border:1px solid #93C6FF;\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius:5px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 0);\n"
"border:1px solid #93C6FF;\n"
"}\n"
"")
        self.frame_botones.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botones.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botones.setObjectName("frame_botones")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_botones)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.button_detect = QtWidgets.QPushButton(self.frame_botones)
        self.button_detect.setMinimumSize(QtCore.QSize(0, 38))
        self.button_detect.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/inteligencia-artificial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_detect.setIcon(icon3)
        self.button_detect.setIconSize(QtCore.QSize(35, 35))
        self.button_detect.setObjectName("button_detect")
        self.verticalLayout_5.addWidget(self.button_detect)
        self.button_conf = QtWidgets.QPushButton(self.frame_botones)
        self.button_conf.setMinimumSize(QtCore.QSize(0, 38))
        self.button_conf.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/confirmar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_conf.setIcon(icon4)
        self.button_conf.setIconSize(QtCore.QSize(35, 35))
        self.button_conf.setObjectName("button_conf")
        self.verticalLayout_5.addWidget(self.button_conf)
        self.button_send = QtWidgets.QPushButton(self.frame_botones)
        self.button_send.setMinimumSize(QtCore.QSize(0, 38))
        self.button_send.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/enviar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_send.setIcon(icon5)
        self.button_send.setIconSize(QtCore.QSize(30, 30))
        self.button_send.setObjectName("button_send")
        self.verticalLayout_5.addWidget(self.button_send)
        self.verticalLayout_4.addWidget(self.frame_botones)
        self.frame_datos2 = QtWidgets.QFrame(self.frame_datos)
        self.frame_datos2.setStyleSheet("QFrame{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(69, 74, 88);\n"
"border-radius:30px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"QLabel{\n"
"font: 14pt \"Consolas\";\n"
"color: rgb(255, 255,255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"border:1px solid #93C6FF;\n"
"border-radius:5px;\n"
"background-color: rgb(70, 70, 70);\n"
"font: 13pt \"Consolas\";\n"
"color: rgb(255, 255,255);\n"
"}\n"
"\n"
"QTextBrowser{\n"
"border-radius:5px;\n"
"border:1px solid #93C6FF;\n"
"background-color: rgb(70, 70, 70);\n"
"font: 13pt \"Consolas\";\n"
"color: rgb(255, 255,255);\n"
"}")
        self.frame_datos2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_datos2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_datos2.setObjectName("frame_datos2")
        self.label_3 = QtWidgets.QLabel(self.frame_datos2)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 231, 30))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_datos2)
        self.label_4.setGeometry(QtCore.QRect(0, 110, 221, 30))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_datos2)
        self.label_5.setGeometry(QtCore.QRect(0, 350, 181, 30))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_datos2)
        self.label_6.setGeometry(QtCore.QRect(0, 10, 221, 30))
        self.label_6.setObjectName("label_6")
        self.button_plas = QtWidgets.QPushButton(self.frame_datos2)
        self.button_plas.setGeometry(QtCore.QRect(296, 162, 60, 60))
        self.button_plas.setStyleSheet("")
        self.button_plas.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/mas (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_plas.setIcon(icon6)
        self.button_plas.setIconSize(QtCore.QSize(70, 70))
        self.button_plas.setObjectName("button_plas")
        self.out_sticks = QtWidgets.QTextBrowser(self.frame_datos2)
        self.out_sticks.setGeometry(QtCore.QRect(261, 56, 130, 38))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.out_sticks.setFont(font)
        self.out_sticks.setObjectName("out_sticks")
        self.out_diameter = QtWidgets.QTextBrowser(self.frame_datos2)
        self.out_diameter.setGeometry(QtCore.QRect(261, 106, 130, 38))
        self.out_diameter.setObjectName("out_diameter")
        self.out_correction = QtWidgets.QTextBrowser(self.frame_datos2)
        self.out_correction.setGeometry(QtCore.QRect(261, 226, 130, 38))
        self.out_correction.setObjectName("out_correction")
        self.out_total = QtWidgets.QTextBrowser(self.frame_datos2)
        self.out_total.setGeometry(QtCore.QRect(261, 346, 130, 38))
        self.out_total.setObjectName("out_total")
        self.in_npackge = QtWidgets.QLineEdit(self.frame_datos2)
        self.in_npackge.setGeometry(QtCore.QRect(261, 6, 130, 38))
        self.in_npackge.setStyleSheet("")
        self.in_npackge.setText("")
        self.in_npackge.setObjectName("in_npackge")
        self.button_less = QtWidgets.QPushButton(self.frame_datos2)
        self.button_less.setGeometry(QtCore.QRect(296, 270, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_less.sizePolicy().hasHeightForWidth())
        self.button_less.setSizePolicy(sizePolicy)
        self.button_less.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_less.setStyleSheet("")
        self.button_less.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/menos (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_less.setIcon(icon7)
        self.button_less.setIconSize(QtCore.QSize(70, 70))
        self.button_less.setObjectName("button_less")
        self.label_7 = QtWidgets.QLabel(self.frame_datos2)
        self.label_7.setGeometry(QtCore.QRect(0, 230, 261, 30))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.frame_datos2)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 5)
        self.horizontalLayout_2.addWidget(self.frame_datos)
        self.frame_imagen = QtWidgets.QFrame(self.frame_inferior)
        self.frame_imagen.setMinimumSize(QtCore.QSize(600, 552))
        self.frame_imagen.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_imagen.setStyleSheet("QFrame{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"")
        self.frame_imagen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_imagen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_imagen.setObjectName("frame_imagen")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_imagen)
        self.verticalLayout_3.setContentsMargins(40, 0, 40, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_imagen)
        self.tabWidget.setMaximumSize(QtCore.QSize(505, 530))
        self.tabWidget.setStyleSheet(" QTabBar::tab {\n"
"font: 14pt \"Consolas\";\n"
"color:rgb(255, 255,255);\n"
"border:2px solid #93C6FF;\n"
"background-color: rgb(70, 70, 70);         \n"
"                min-width:130px; /* Cambia el ancho mínimo de los botones */\n"
"                padding: 8px; /* Cambia el espacio interno de los botones */\n"
"            }\n"
"\n"
"            QTabBar::tab:selected {\n"
"font: 14pt \"Consolas\";\n"
"color:rgb(255, 255,255);\n"
"border:3px solid #93C6FF;\n"
"background-color: rgb(0, 0, 0);    \n"
"            }\n"
"QTabWidget::pane {\n"
"     border:3px solid #93C6FF;\n"
"background-color: rgb(70, 70, 70);    \n"
"            }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.out_img = QtWidgets.QLabel(self.tab)
        self.out_img.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.out_img.setText("")
        self.out_img.setAlignment(QtCore.Qt.AlignCenter)
        self.out_img.setObjectName("out_img")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.out_detect = QtWidgets.QLabel(self.tab_2)
        self.out_detect.setGeometry(QtCore.QRect(0, 0, 500, 500))
        self.out_detect.setText("")
        self.out_detect.setObjectName("out_detect")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_2.addWidget(self.frame_imagen)
        self.verticalLayout_2.addWidget(self.frame_inferior)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Detección de Palos "))
        self.button_detect.setText(_translate("MainWindow", "Detectar  "))
        self.button_conf.setText(_translate("MainWindow", "Confirmar "))
        self.button_send.setText(_translate("MainWindow", "Enviar    "))
        self.label_3.setText(_translate("MainWindow", "Palos Detectados:"))
        self.label_4.setText(_translate("MainWindow", "Diametro Promedio:"))
        self.label_5.setText(_translate("MainWindow", "Palos Totales:"))
        self.label_6.setText(_translate("MainWindow", "N° de Paquete:"))
        self.in_npackge.setPlaceholderText(_translate("MainWindow", "Escribe N°"))
        self.label_7.setText(_translate("MainWindow", "Correción Detección:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Fotografia"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Detección"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
