# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detect_sticks.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 416)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QLabel{\n"
"color:rgb(255, 255,255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"border:0px;\n"
"background-color:#93C6FF;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:5px;\n"
"border-color:rgb(170, 4, 7);\n"
"background-color: rgb(170, 4, 7);\n"
"}\n"
"QLabel{\n"
"font: 16pt \"Consolas\";\n"
"}\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(15, 5, 2, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_superior)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(477, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(self.frame)
        self.frame_inferior.setStyleSheet("")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_datos = QtWidgets.QFrame(self.frame_inferior)
        self.frame_datos.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_datos.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_datos.setStyleSheet("QFrame{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"")
        self.frame_datos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_datos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_datos.setObjectName("frame_datos")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_datos)
        self.verticalLayout_4.setContentsMargins(15, 0, 5, 5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_botones = QtWidgets.QFrame(self.frame_datos)
        self.frame_botones.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_botones.setStyleSheet("QFrame{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 14pt \"Consolas\";\n"
"color:rgb(255, 255,255);\n"
"border:1px solid #93C6FF;\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius:5px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 0);\n"
"border:1px solid #93C6FF;\n"
"}\n"
"")
        self.frame_botones.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botones.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botones.setObjectName("frame_botones")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_botones)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.button_detect = QtWidgets.QPushButton(self.frame_botones)
        self.button_detect.setMinimumSize(QtCore.QSize(0, 20))
        self.button_detect.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/inteligencia-artificial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_detect.setIcon(icon)
        self.button_detect.setIconSize(QtCore.QSize(35, 35))
        self.button_detect.setObjectName("button_detect")
        self.verticalLayout_5.addWidget(self.button_detect)
        self.button_conf = QtWidgets.QPushButton(self.frame_botones)
        self.button_conf.setMinimumSize(QtCore.QSize(0, 20))
        self.button_conf.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/confirmar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_conf.setIcon(icon1)
        self.button_conf.setIconSize(QtCore.QSize(35, 35))
        self.button_conf.setObjectName("button_conf")
        self.verticalLayout_5.addWidget(self.button_conf)
        self.button_send = QtWidgets.QPushButton(self.frame_botones)
        self.button_send.setMinimumSize(QtCore.QSize(0, 20))
        self.button_send.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/enviar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_send.setIcon(icon2)
        self.button_send.setIconSize(QtCore.QSize(30, 30))
        self.button_send.setObjectName("button_send")
        self.verticalLayout_5.addWidget(self.button_send)
        self.verticalLayout_4.addWidget(self.frame_botones)
        self.frame_2 = QtWidgets.QFrame(self.frame_datos)
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(69, 74, 88);\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"QLabel{\n"
"font: 13pt \"Consolas\";\n"
"color: rgb(255, 255,255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"border:1px solid #93C6FF;\n"
"border-radius:5px;\n"
"background-color: rgb(70, 70, 70);\n"
"font: 12pt \"Consolas\";\n"
"color: rgb(255, 255,255);\n"
"}\n"
"\n"
"QTextBrowser{\n"
"border-radius:5px;\n"
"border:1px solid #93C6FF;\n"
"background-color: rgb(70, 70, 70);\n"
"font: 12pt \"Consolas\";\n"
"color: rgb(255, 255,255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_11 = QtWidgets.QFrame(self.frame_2)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_8 = QtWidgets.QLabel(self.frame_11)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 168, 33))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.in_npackage = QtWidgets.QLineEdit(self.frame_11)
        self.in_npackage.setGeometry(QtCore.QRect(242, 0, 131, 33))
        self.in_npackage.setMinimumSize(QtCore.QSize(0, 33))
        self.in_npackage.setObjectName("in_npackage")
        self.verticalLayout_8.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 231, 33))
        self.label_9.setMinimumSize(QtCore.QSize(0, 33))
        self.label_9.setObjectName("label_9")
        self.out_sticks = QtWidgets.QTextBrowser(self.frame_12)
        self.out_sticks.setGeometry(QtCore.QRect(242, 0, 131, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_sticks.sizePolicy().hasHeightForWidth())
        self.out_sticks.setSizePolicy(sizePolicy)
        self.out_sticks.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.out_sticks.setFont(font)
        self.out_sticks.setObjectName("out_sticks")
        self.verticalLayout_8.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_2)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 221, 33))
        self.label_10.setMinimumSize(QtCore.QSize(0, 33))
        self.label_10.setObjectName("label_10")
        self.out_diameter = QtWidgets.QTextBrowser(self.frame_13)
        self.out_diameter.setGeometry(QtCore.QRect(242, 0, 131, 33))
        self.out_diameter.setMinimumSize(QtCore.QSize(0, 33))
        self.out_diameter.setObjectName("out_diameter")
        self.verticalLayout_8.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_2)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.button_plas = QtWidgets.QPushButton(self.frame_14)
        self.button_plas.setGeometry(QtCore.QRect(280, 0, 43, 43))
        self.button_plas.setStyleSheet("")
        self.button_plas.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/mas (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_plas.setIcon(icon3)
        self.button_plas.setIconSize(QtCore.QSize(55, 55))
        self.button_plas.setObjectName("button_plas")
        self.verticalLayout_8.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_2)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_12 = QtWidgets.QLabel(self.frame_15)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 261, 33))
        self.label_12.setObjectName("label_12")
        self.out_correction = QtWidgets.QTextBrowser(self.frame_15)
        self.out_correction.setGeometry(QtCore.QRect(242, 0, 131, 33))
        self.out_correction.setMinimumSize(QtCore.QSize(0, 33))
        self.out_correction.setObjectName("out_correction")
        self.verticalLayout_8.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_2)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.button_less = QtWidgets.QPushButton(self.frame_16)
        self.button_less.setGeometry(QtCore.QRect(280, 0, 43, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_less.sizePolicy().hasHeightForWidth())
        self.button_less.setSizePolicy(sizePolicy)
        self.button_less.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_less.setStyleSheet("")
        self.button_less.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/menos (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_less.setIcon(icon4)
        self.button_less.setIconSize(QtCore.QSize(55, 55))
        self.button_less.setObjectName("button_less")
        self.verticalLayout_8.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_2)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_11 = QtWidgets.QLabel(self.frame_17)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 181, 33))
        self.label_11.setObjectName("label_11")
        self.out_total = QtWidgets.QTextBrowser(self.frame_17)
        self.out_total.setGeometry(QtCore.QRect(242, 0, 131, 33))
        self.out_total.setMinimumSize(QtCore.QSize(0, 33))
        self.out_total.setObjectName("out_total")
        self.verticalLayout_8.addWidget(self.frame_17)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 6)
        self.horizontalLayout_2.addWidget(self.frame_datos)
        self.frame_imagen = QtWidgets.QFrame(self.frame_inferior)
        self.frame_imagen.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_imagen.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.frame_imagen.setStyleSheet("QFrame{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"")
        self.frame_imagen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_imagen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_imagen.setObjectName("frame_imagen")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_imagen)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_imagen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(640, 600))
        self.tabWidget.setStyleSheet(" QTabBar::tab {\n"
"font: 13pt \"Consolas\";\n"
"color:rgb(255, 255,255);\n"
"border:2px solid #93C6FF;\n"
"background-color: rgb(70, 70, 70);\n"
"                min-width:130px; /* Cambia el ancho mínimo de los botones */\n"
"                padding: 5px; /* Cambia el espacio interno de los botones */         \n"
"\n"
"            }\n"
"\n"
"QTabBar::tab:selected {\n"
"font: 13pt \"Consolas\";\n"
"color:rgb(255, 255,255);\n"
"background-color: rgb(0, 0, 0);    \n"
"            }\n"
"QTabWidget::pane {\n"
" border:3px solid #93C6FF;    \n"
"background-color: rgb(70, 70, 70);    \n"
"            }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.out_img = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_img.sizePolicy().hasHeightForWidth())
        self.out_img.setSizePolicy(sizePolicy)
        self.out_img.setMinimumSize(QtCore.QSize(300, 300))
        self.out_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.out_img.setAlignment(QtCore.Qt.AlignCenter)
        self.out_img.setObjectName("out_img")
        self.verticalLayout_3.addWidget(self.out_img)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.out_detect = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_detect.sizePolicy().hasHeightForWidth())
        self.out_detect.setSizePolicy(sizePolicy)
        self.out_detect.setMinimumSize(QtCore.QSize(269, 269))
        self.out_detect.setMaximumSize(QtCore.QSize(640, 640))
        self.out_detect.setAlignment(QtCore.Qt.AlignCenter)
        self.out_detect.setObjectName("out_detect")
        self.verticalLayout_7.addWidget(self.out_detect)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_imagen)
        self.verticalLayout_2.addWidget(self.frame_inferior)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Detección de Palos "))
        self.button_detect.setText(_translate("MainWindow", "Detectar  "))
        self.button_conf.setText(_translate("MainWindow", "Confirmar "))
        self.button_send.setText(_translate("MainWindow", "Enviar    "))
        self.label_8.setText(_translate("MainWindow", "N° de Paquete:"))
        self.label_9.setText(_translate("MainWindow", "Palos Detectados:"))
        self.label_10.setText(_translate("MainWindow", "Diametro Promedio:"))
        self.label_12.setText(_translate("MainWindow", "Correción Detección:"))
        self.label_11.setText(_translate("MainWindow", "Palos Totales:"))
        self.out_img.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Fotografia"))
        self.out_detect.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Detección"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
