# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detect_sticks.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"border:0px;\n"
"background-color: rgb(20, 200,230);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:5px solid #aa00ff;\n"
"background-color: rgb(20, 200,230);\n"
"}\n"
"\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(2, 5, 2, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_superior)
        self.label.setStyleSheet("\n"
"font: 900 16pt \"Arial Black\";\n"
"color: rgb(20, 200, 230);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(477, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_minimize = QtWidgets.QPushButton(self.frame_superior)
        self.button_minimize.setMaximumSize(QtCore.QSize(30, 30))
        self.button_minimize.setStyleSheet("")
        self.button_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_minimize.setIcon(icon)
        self.button_minimize.setIconSize(QtCore.QSize(25, 25))
        self.button_minimize.setObjectName("button_minimize")
        self.horizontalLayout.addWidget(self.button_minimize)
        self.button_maximize = QtWidgets.QPushButton(self.frame_superior)
        self.button_maximize.setMaximumSize(QtCore.QSize(30, 30))
        self.button_maximize.setStyleSheet("")
        self.button_maximize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/maximizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_maximize.setIcon(icon1)
        self.button_maximize.setIconSize(QtCore.QSize(25, 25))
        self.button_maximize.setObjectName("button_maximize")
        self.horizontalLayout.addWidget(self.button_maximize)
        self.button_close = QtWidgets.QPushButton(self.frame_superior)
        self.button_close.setMaximumSize(QtCore.QSize(30, 30))
        self.button_close.setStyleSheet("")
        self.button_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon2)
        self.button_close.setIconSize(QtCore.QSize(25, 25))
        self.button_close.setObjectName("button_close")
        self.horizontalLayout.addWidget(self.button_close)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(self.frame)
        self.frame_inferior.setStyleSheet("")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_imagen = QtWidgets.QFrame(self.frame_inferior)
        self.frame_imagen.setMinimumSize(QtCore.QSize(700, 552))
        self.frame_imagen.setStyleSheet("QFrame{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"")
        self.frame_imagen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_imagen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_imagen.setObjectName("frame_imagen")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_imagen)
        self.verticalLayout_3.setContentsMargins(90, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_imagen)
        self.stackedWidget.setMaximumSize(QtCore.QSize(510, 510))
        self.stackedWidget.setStyleSheet("background-color: rgb(131, 131, 131);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.camara = QtWidgets.QWidget()
        self.camara.setObjectName("camara")
        self.out_camara = QtWidgets.QLabel(self.camara)
        self.out_camara.setGeometry(QtCore.QRect(5, 5, 500, 500))
        self.out_camara.setMinimumSize(QtCore.QSize(500, 500))
        self.out_camara.setText("")
        self.out_camara.setAlignment(QtCore.Qt.AlignCenter)
        self.out_camara.setObjectName("out_camara")
        self.stackedWidget.addWidget(self.camara)
        self.detection = QtWidgets.QWidget()
        self.detection.setObjectName("detection")
        self.out_processing = QtWidgets.QLabel(self.detection)
        self.out_processing.setGeometry(QtCore.QRect(5, 5, 500, 500))
        self.out_processing.setMinimumSize(QtCore.QSize(500, 500))
        self.out_processing.setText("")
        self.out_processing.setAlignment(QtCore.Qt.AlignCenter)
        self.out_processing.setObjectName("out_processing")
        self.stackedWidget.addWidget(self.detection)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_imagen)
        self.frame_datos = QtWidgets.QFrame(self.frame_inferior)
        self.frame_datos.setMinimumSize(QtCore.QSize(320, 0))
        self.frame_datos.setStyleSheet("QFrame{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 900 13pt \"Arial Black\";\n"
"color: rgb(20, 200,230);\n"
"border:1px solid white;\n"
"background-color: rgb(69, 74, 88);\n"
"\n"
"}\n"
"QLabel{\n"
"font: 900 13pt \"Arial Black\";\n"
"color: rgb(20, 200,230);\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"")
        self.frame_datos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_datos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_datos.setObjectName("frame_datos")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_datos)
        self.verticalLayout_4.setContentsMargins(0, 10, 10, 10)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_botones = QtWidgets.QFrame(self.frame_datos)
        self.frame_botones.setStyleSheet("Qframe:{\n"
"background-color: rgb(69, 74, 88);\n"
"}\n"
"QPushButton{\n"
"font: 900 13pt \"Arial Black\";\n"
"color: rgb(20, 200,230);\n"
"border:1px solid white;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"")
        self.frame_botones.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botones.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botones.setObjectName("frame_botones")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_botones)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.button_detect = QtWidgets.QPushButton(self.frame_botones)
        self.button_detect.setMinimumSize(QtCore.QSize(0, 38))
        self.button_detect.setIconSize(QtCore.QSize(30, 30))
        self.button_detect.setObjectName("button_detect")
        self.verticalLayout_5.addWidget(self.button_detect)
        self.button_conf = QtWidgets.QPushButton(self.frame_botones)
        self.button_conf.setMinimumSize(QtCore.QSize(0, 38))
        self.button_conf.setIconSize(QtCore.QSize(30, 3))
        self.button_conf.setObjectName("button_conf")
        self.verticalLayout_5.addWidget(self.button_conf)
        self.button_send = QtWidgets.QPushButton(self.frame_botones)
        self.button_send.setMinimumSize(QtCore.QSize(0, 38))
        self.button_send.setIconSize(QtCore.QSize(30, 30))
        self.button_send.setObjectName("button_send")
        self.verticalLayout_5.addWidget(self.button_send)
        self.verticalLayout_4.addWidget(self.frame_botones)
        self.frame_datos2 = QtWidgets.QFrame(self.frame_datos)
        self.frame_datos2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_datos2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_datos2.setObjectName("frame_datos2")
        self.label_3 = QtWidgets.QLabel(self.frame_datos2)
        self.label_3.setGeometry(QtCore.QRect(0, 80, 181, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_datos2)
        self.label_4.setGeometry(QtCore.QRect(0, 140, 191, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_datos2)
        self.label_5.setGeometry(QtCore.QRect(0, 340, 181, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_datos2)
        self.label_6.setGeometry(QtCore.QRect(0, 30, 221, 31))
        self.label_6.setObjectName("label_6")
        self.button_plas = QtWidgets.QPushButton(self.frame_datos2)
        self.button_plas.setGeometry(QtCore.QRect(205, 200, 100, 41))
        self.button_plas.setStyleSheet("font: 900 24pt \"Arial Black\";\n"
"border:0px solid white;")
        self.button_plas.setObjectName("button_plas")
        self.out_sticks = QtWidgets.QTextBrowser(self.frame_datos2)
        self.out_sticks.setGeometry(QtCore.QRect(205, 80, 100, 31))
        self.out_sticks.setObjectName("out_sticks")
        self.out_diameter = QtWidgets.QTextBrowser(self.frame_datos2)
        self.out_diameter.setGeometry(QtCore.QRect(205, 140, 100, 31))
        self.out_diameter.setObjectName("out_diameter")
        self.out_correction = QtWidgets.QTextBrowser(self.frame_datos2)
        self.out_correction.setGeometry(QtCore.QRect(205, 250, 100, 31))
        self.out_correction.setObjectName("out_correction")
        self.out_total = QtWidgets.QTextBrowser(self.frame_datos2)
        self.out_total.setGeometry(QtCore.QRect(205, 340, 100, 31))
        self.out_total.setObjectName("out_total")
        self.in_npackge = QtWidgets.QLineEdit(self.frame_datos2)
        self.in_npackge.setGeometry(QtCore.QRect(205, 30, 100, 31))
        self.in_npackge.setStyleSheet("background-color: rgb(131, 131, 131);")
        self.in_npackge.setObjectName("in_npackge")
        self.button_less = QtWidgets.QPushButton(self.frame_datos2)
        self.button_less.setGeometry(QtCore.QRect(205, 290, 100, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_less.sizePolicy().hasHeightForWidth())
        self.button_less.setSizePolicy(sizePolicy)
        self.button_less.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_less.setStyleSheet("font: 900 35pt \"Arial Black\";\n"
"border:0px solid white;")
        self.button_less.setObjectName("button_less")
        self.label_7 = QtWidgets.QLabel(self.frame_datos2)
        self.label_7.setGeometry(QtCore.QRect(0, 250, 201, 31))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.frame_datos2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 3)
        self.horizontalLayout_2.addWidget(self.frame_datos)
        self.verticalLayout_2.addWidget(self.frame_inferior)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Detección de Palos "))
        self.button_detect.setText(_translate("MainWindow", "Detectar"))
        self.button_conf.setText(_translate("MainWindow", "Confirmar"))
        self.button_send.setText(_translate("MainWindow", "Enviar"))
        self.label_3.setText(_translate("MainWindow", "Palos Detectados:"))
        self.label_4.setText(_translate("MainWindow", "Diametro Promedio:"))
        self.label_5.setText(_translate("MainWindow", "Palos Totales:"))
        self.label_6.setText(_translate("MainWindow", "N° de Paquete:"))
        self.button_plas.setText(_translate("MainWindow", "+"))
        self.button_less.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "Correción Detección:"))
