
save_txt: True
line_thickness: 2
hide_labels: True
device: "cpu"
source: ../image
img_size: 640

sticks:
  weights: weights/sticks/best.pt
  results: runs/detect/sticks
  conf_thres: 0.60
  iou_thres: 0.45

packages:
  weights: weights/packages/best.pt
  results: runs/detect/packages
  conf_thres: 0.50
  iou_thres: 0.45


  