
save_txt: True
line_thickness: 2
hide_labels: True
device: "cpu"
source: ../images
img_size_w: 640
img_size_h: 640
#img_size: [3964,2464]

images:
  results: ../images/main_packages

sticks:
  weights: weights/sticks/best.pt
  results: ../images/sticks
  conf_thres: 0.60
  iou_thres: 0.45

packages:
  weights: weights/packages/best.pt
  results: ../images/packages
  conf_thres: 0.50
  iou_thres: 0.45

post-process:
  avg_package_diameter: 130


  